### ISSUE TITLE
The text for project name(s) is illegible when some light themes are used.

### ISSUE THREAD

**Issue by M0JXD** [Stazed/non-FL#1]
Hi,

First off I want to say thank you for rebooting the Non suite! Your additions are great and I'm looking forward to using it more.

When using the themes "muted" and "washed out" the project text (Saying "Test_Session" in my example) can be hard to read:

![Illegible Text](https://github.com/Stazed/non-FL/assets/94254558/76225fdc-d73f-4a41-8788-1c0a75d1bbfc)

I think this is the relevant repo for this issue? If not I can open it in a different one.

Thank you again!

**Comment by Stazed** [comment]
Just pushed a commit to here and to the wip branches of timeline and mixer that should make the lighter themes work better. You will need to update the submodule for both the timeline and mixer.

Also, it would be better to open any issues directly with the mixer or timeline even if it is entirely submodule related. It makes it easier to track on my end.

Thanks for the useful report!

**Comment by M0JXD** [comment]
Superb, the fix is great! Thank you for implementing it so quick :)

![Screenshot from 2024-07-01 15-50-41](https://github.com/Stazed/non-FL/assets/94254558/b71236de-1b58-4e0d-834a-4bca700d7628)

Duly noted regarding issues. For anything affecting both would you prefer them to be with the mixer or timeline repository?

As an aside, I noticed you've been working on seq42/32 which works as an alternative for Non Sequencer (Which is funny because JML created it to replace Seq24). Are you working for maximum compatibility with a specific session manager? I've been using RaySession for now but if you're testing with Agordejo/New-SM or the original Non-SM I'd prefer to use that because the protocols seem to differ slightly.

**Comment by Stazed** [comment]
If the issue affects both projects, then opening a PR in both would be best.

For session issues I test Agordejo, New-SM and RaySession. It should work in all three. I'm not testing original Non-SM.
